// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wufknidkprsagfpejrsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1ZmtuaWRrcHJzYWdmcGVqcnN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1NjYyNTQsImV4cCI6MjA1OTE0MjI1NH0.uq5hxpX5z9d9jk35Y8uNKpemJlRay7h0-vI3Bn12VPo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);